import type { TraceCommitSummary } from '../../core/types';

function StatPill({ label, value, tone }: { label: string; value: string; tone: 'ai' | 'human' | 'mixed' | 'unknown' }) {
  const className =
    tone === 'ai'
      ? 'pill-trace-ai'
      : tone === 'human'
        ? 'pill-trace-human'
        : tone === 'mixed'
          ? 'pill-trace-mixed'
          : 'pill-trace-unknown';

  return (
    <span className={`inline-flex items-center gap-2 ${className}`}>
      <span className="text-[10px] uppercase tracking-wide">{label}</span>
      <span className="font-semibold tabular-nums">{value}</span>
    </span>
  );
}

export function AgentTraceSummary(props: {
  summary?: TraceCommitSummary;
  onExport?: () => void;
  hasFiles: boolean;
}) {
  const { summary, onExport, hasFiles } = props;
  const aiPercent = summary?.aiPercent ?? 0;

  return (
    <div className="card p-5">
      <div className="flex items-center justify-between">
        <div>
          <div className="section-header">AGENT TRACE</div>
          <div className="section-subheader mt-0.5">who changed what</div>
        </div>
        {onExport ? (
          <button
            type="button"
            className="inline-flex items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-1.5 text-xs font-semibold text-stone-600 hover:bg-stone-50"
            onClick={onExport}
            disabled={!hasFiles}
            aria-disabled={!hasFiles}
          >
            Export Agent Trace
          </button>
        ) : null}
      </div>

      {!summary ? (
        <div className="mt-4 rounded-lg border border-dashed border-stone-200 bg-stone-50 px-4 py-3 text-sm text-stone-500">
          No Agent Trace records found for this commit yet.
        </div>
      ) : (
        <div className="mt-4 space-y-4">
          <div className="flex items-center gap-3">
            <div className="trace-bar">
              <div className="trace-bar-fill" style={{ width: `${aiPercent}%` }} />
            </div>
            <div className="text-sm font-semibold text-stone-700">AI {aiPercent}%</div>
          </div>

          <div className="flex flex-wrap gap-2">
            <StatPill label="AI" value={`${summary.aiLines}`} tone="ai" />
            <StatPill label="Human" value={`${summary.humanLines}`} tone="human" />
            <StatPill label="Mixed" value={`${summary.mixedLines}`} tone="mixed" />
            <StatPill label="Unknown" value={`${summary.unknownLines}`} tone="unknown" />
          </div>

          <div className="text-xs text-stone-500 leading-relaxed">
            Agent Trace highlights which lines were generated by AI versus edited by humans. It is a
            helpful guide, not a legal ownership claim.
          </div>

          {summary.modelIds.length > 0 ? (
            <div className="text-xs text-stone-400">
              Models: {summary.modelIds.join(', ')}
            </div>
          ) : (
            <div className="text-xs text-stone-400">Models: unknown</div>
          )}
        </div>
      )}
    </div>
  );
}
